;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Buff.Passive.ForsetForce",DevComment="森林之力")
GameplayTagList=(Tag="Buff.Passive.CounterVine",DevComment="")
GameplayTagList=(Tag="Buff.Passive.LoneWolf",DevComment="")
GameplayTagList=(Tag="Buff.Status.Bleed",DevComment="")
GameplayTagList=(Tag="Buff.Status.EnemyMissDamageBoost",DevComment="")
GameplayTagList=(Tag="Buff.Status.EnemyMissSpeedBoost",DevComment="")
GameplayTagList=(Tag="Buff.Status.Rooted",DevComment="")

