;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Unit.Attack.Magic",DevComment="")
+GameplayTagList=(Tag="Unit.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Unit.Attack.Ranged",DevComment="")
+GameplayTagList=(Tag="Unit.Career.GatherAP",DevComment="聚灵")
+GameplayTagList=(Tag="Unit.Race.Wolf",DevComment="狼")
+GameplayTagList=(Tag="UnitTag.Accurate",DevComment="")
+GameplayTagList=(Tag="UnitTag.Brave",DevComment="")
+GameplayTagList=(Tag="UnitTag.Mad",DevComment="")
+GameplayTagList=(Tag="UnitTag.Silent",DevComment="")
+GameplayTagList=(Tag="UnitTag.Strong",DevComment="")

